-- Header & Footer Customization Migration
-- Version: 1.0.0
-- Date: 2025-11-01
-- Description: Add columns to profiles table for header and footer customization

-- ============================================================================
-- ADD HEADER & FOOTER COLUMNS TO PROFILES TABLE
-- ============================================================================

-- Header Customization Columns
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS header_logo TEXT,
ADD COLUMN IF NOT EXISTS header_client_logo TEXT,
ADD COLUMN IF NOT EXISTS header_show_client_logo BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS header_company_name TEXT,
ADD COLUMN IF NOT EXISTS header_tagline TEXT,
ADD COLUMN IF NOT EXISTS header_bg_color TEXT DEFAULT '#DC2626',
ADD COLUMN IF NOT EXISTS header_text_color TEXT DEFAULT '#FFFFFF',
ADD COLUMN IF NOT EXISTS header_layout TEXT DEFAULT 'horizontal' CHECK (header_layout IN ('horizontal', 'vertical')),
ADD COLUMN IF NOT EXISTS header_show_contact BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS header_contact_phone TEXT,
ADD COLUMN IF NOT EXISTS header_contact_email TEXT,
ADD COLUMN IF NOT EXISTS header_contact_website TEXT,
ADD COLUMN IF NOT EXISTS header_contact_address TEXT;

-- Footer Customization Columns
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS footer_text TEXT,
ADD COLUMN IF NOT EXISTS footer_bg_color TEXT DEFAULT '#1F2937',
ADD COLUMN IF NOT EXISTS footer_text_color TEXT DEFAULT '#FFFFFF',
ADD COLUMN IF NOT EXISTS footer_font_size INTEGER DEFAULT 12,
ADD COLUMN IF NOT EXISTS footer_alignment TEXT DEFAULT 'center' CHECK (footer_alignment IN ('left', 'center', 'right')),
ADD COLUMN IF NOT EXISTS footer_show_border BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS footer_border_color TEXT DEFAULT '#DC2626';

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

-- No specific indexes needed for these columns as they're accessed with user_id which already has indexes

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON COLUMN profiles.header_logo IS 'Base64 encoded logo image for proposal headers';
COMMENT ON COLUMN profiles.header_company_name IS 'Company name displayed in proposal header';
COMMENT ON COLUMN profiles.header_tagline IS 'Tagline or slogan displayed in proposal header';
COMMENT ON COLUMN profiles.header_bg_color IS 'Header background color (hex format)';
COMMENT ON COLUMN profiles.header_text_color IS 'Header text color (hex format)';
COMMENT ON COLUMN profiles.header_layout IS 'Header layout orientation (horizontal or vertical)';
COMMENT ON COLUMN profiles.header_show_contact IS 'Whether to show contact information in header';
COMMENT ON COLUMN profiles.header_contact_phone IS 'Phone number displayed in header';
COMMENT ON COLUMN profiles.header_contact_email IS 'Email address displayed in header';
COMMENT ON COLUMN profiles.header_contact_website IS 'Website URL displayed in header';
COMMENT ON COLUMN profiles.header_contact_address IS 'Physical address displayed in header';

COMMENT ON COLUMN profiles.footer_text IS 'Text displayed in proposal footer';
COMMENT ON COLUMN profiles.footer_bg_color IS 'Footer background color (hex format)';
COMMENT ON COLUMN profiles.footer_text_color IS 'Footer text color (hex format)';
COMMENT ON COLUMN profiles.footer_font_size IS 'Footer text font size in pixels';
COMMENT ON COLUMN profiles.footer_alignment IS 'Footer text alignment (left, center, or right)';
COMMENT ON COLUMN profiles.footer_show_border IS 'Whether to show top border in footer';
COMMENT ON COLUMN profiles.footer_border_color IS 'Footer border color (hex format)';

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================

-- This migration adds comprehensive header and footer customization options
-- to the profiles table, allowing users to:
--
-- Header Features:
-- - Upload and display company logos
-- - Customize company name and tagline
-- - Choose background and text colors
-- - Select horizontal or vertical layout
-- - Include contact information (phone, email, website, address)
--
-- Footer Features:
-- - Add custom footer text
-- - Customize background and text colors
-- - Set font size
-- - Choose text alignment
-- - Add optional top border with custom color
--
-- All customizations are stored per user (via user_id/profile id) and will
-- be applied to all proposals generated by that user unless overridden
-- at the proposal level.
